package cn.ebooboo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBookResult<M extends BaseBookResult<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setBookId(java.lang.Integer audioId) {
		set("book_id", audioId);
	}

	public java.lang.Integer getBookId() {
		return get("book_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setAudioIsDone(java.lang.Integer isDone) {
		set("audio_is_done", isDone);
	}

	public java.lang.Integer getAudioIsDone() {
		return get("audio_is_done");
	}
	
	public void setAssistIsDone(java.lang.Integer isDone) {
		set("assist_is_done", isDone);
	}
	
	public java.lang.Integer getAssistIsDone() {
		return get("assist_is_done");
	}
	
	public void setQuizIsDone(java.lang.Integer isDone) {
		set("quiz_is_done", isDone);
	}
	
	public java.lang.Integer getQuizIsDone() {
		return get("quiz_is_done");
	}

}
