package cn.ebooboo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuizResult<M extends BaseQuizResult<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setQuizId(java.lang.Integer quizId) {
		set("quiz_id", quizId);
	}

	public java.lang.Integer getQuizId() {
		return get("quiz_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setIsRight(java.lang.Integer isRight) {
		set("is_right", isRight);
	}

	public java.lang.Integer getIsRight() {
		return get("is_right");
	}

}
