package cn.ebooboo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAssist<M extends BaseAssist<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setChapterId(java.lang.Integer chapterId) {
		set("chapter_id", chapterId);
	}

	public java.lang.Integer getChapterId() {
		return get("chapter_id");
	}

	public void setWord(java.lang.String word) {
		set("word", word);
	}

	public java.lang.String getWord() {
		return get("word");
	}
	
	public void setExample(java.lang.String example) {
		set("example", example);
	}
	
	public java.lang.String getExample() {
		return get("example");
	}
	
	public void setEnglishExplanation(java.lang.String englishExplanation) {
		set("english_explanation", englishExplanation);
	}
	
	public java.lang.String getEnglishExplanation() {
		return get("english_explanation");
	}
	
	public void setPicUrl(java.lang.String picUrl) {
		set("pic_url", picUrl);
	}
	
	public java.lang.String getPicUrl() {
		return get("pic_url");
	}

}
