package cn.ebooboo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBook<M extends BaseBook<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}
	
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	public java.lang.String getNo() {
		return get("no");
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setLevel(java.lang.String level) {
		set("level", level);
	}
}
