package cn.ebooboo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuiz<M extends BaseQuiz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setChapterId(java.lang.Integer chapterId) {
		set("chapter_id", chapterId);
	}

	public java.lang.Integer getChapterId() {
		return get("chapter_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setAnswer(java.lang.Integer answer) {
		set("answer", answer);
	}

	public java.lang.Integer getAnswer() {
		return get("answer");
	}

}
