package cn.ebooboo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("assist", "id", Assist.class);
		arp.addMapping("assist_result", "id", AssistResult.class);
		arp.addMapping("audio", "id", Audio.class);
		arp.addMapping("audio_result", "id", AudioResult.class);
		arp.addMapping("book", "id", Book.class);
		arp.addMapping("book_result", "id", BookResult.class);
		arp.addMapping("chapter", "id", Chapter.class);
		arp.addMapping("quiz", "id", Quiz.class);
		arp.addMapping("quiz_option", "id", QuizOption.class);
		arp.addMapping("quiz_result", "id", QuizResult.class);
		arp.addMapping("user", "id", User.class);
	}
}

