package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseAdmin;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class Admin extends BaseAdmin<Admin> {
	public static final Admin dao = new Admin().dao();
}
