package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseAssistResult;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class AssistResult extends BaseAssistResult<AssistResult> {
	
}
