package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseAssist;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class Assist extends BaseAssist<Assist> {

	public static Assist dao = new Assist().dao();
	
}
