package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseAudio;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class Audio extends BaseAudio<Audio> {
	
}
