package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseAudioResult;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class AudioResult extends BaseAudioResult<AudioResult> {
	
}
