package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseBookResult;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class BookResult extends BaseBookResult<BookResult> {
	public static final BookResult dao=new BookResult().dao();
}
