package cn.ebooboo.model;

import org.json.JSONException;
import org.json.JSONObject;

import cn.ebooboo.model.base.BaseBook;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class Book extends BaseBook<Book> {

	public static Book dao = new Book().dao();
	
	public static Book BuildFromJson(JSONObject json) {
		if (json == null) return null;
		
		Book book = new Book();
		try {
			if (json.has("id")) book.set("id", json.getInt("id"));
			if (json.has("name")) book.set("name", json.getString("name"));
		} catch (JSONException e) {
			e.printStackTrace();
		}
		return book;
	}
}
