package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseChapter;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class Chapter extends BaseChapter<Chapter> {

	public static Chapter dao = new Chapter().dao();
	
}
