package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseEffectHourHist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EffectHourHist extends BaseEffectHourHist<EffectHourHist> {
	public static final int SOURCE_FIRST_QUIZ=1;
	public static final int SOURCE_BOOK_QUIZ=2;
	public static final EffectHourHist dao = new EffectHourHist().dao();
}
