package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseQuizResult;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class QuizResult extends BaseQuizResult<QuizResult> {
	
}
