package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseQuiz;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class Quiz extends BaseQuiz<Quiz> {
	
}
