package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseQuizOption;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class QuizOption extends BaseQuizOption<QuizOption> {

	public static final QuizOption dao = new QuizOption().dao();
	
}
