package cn.ebooboo.model;

import cn.ebooboo.model.base.BaseUser;
import cn.ebooboo.util.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model
public class User extends BaseUser<User> {

	public static final User dao = new User().dao();
	
}
